### ISSUE TITLE
Unfollow option: Followed time ago

### ISSUE THREAD

**Issue by tlemens** [tlemens/twitter-mass-follow#12]
> Hello,
> The tool is almost perfect, but I was wondering if it is possible to add an unfollowing option for profiles you follow for a certain time?
> For example: I follow some profiles for 3 days or more, and I want to unfollow only these people and not the new ones or those in white list.
> 
> It could help alot because making a white list of 10 people is great but when it starts to reach 100+ people it becomes long.

**Comment by tlemens** [comment]
> Love the extension, what is the likelihood that there is an option to only unfollow or follow over a time period. So only unfollow those that you followed over 7 days ago.

**Comment by IvanRF** [comment]
> Do you have any thoughts on #12

Well, I didn't check the current code, but when you do a Follow you can save the `data-user-id` and the `time`.
Then, for the Unfollow I don't know if the only option is to simulate a `button` click. If that's all you can do, then again you will have to auto scroll in the `twitter.com/followers` page until you reach every user which matchs the time criteria.

**Comment by IvanRF** [comment]
Also, if you start saving that kind of data it would be better to use [`chrome.storage.sync`](https://developer.chrome.com/extensions/storage) instead of `chrome.storage.local`. That way you can log in to other devices and the user data will be available too. You will probably need more storage: `"permissions": ["storage", "unlimitedStorage"]`.

**Comment by tlemens** [comment]
The sync storage is limited and therefore not suitable.

**Comment by tlemens** [comment]
The problem with saving a timestamp on follow is that sometimes Twitter will reject the follow due to limits. That is why this extension only saves the record ids of unfollowed accounts. Because unfollow always works and gets never rejected.

**Comment by IvanRF** [comment]
You can check if it was rejected by looking at the state of the button. You could use timing events.

**Comment by tlemens** [comment]
So the new behaviour would be:
1) While following
2) store  { userId: timeStamp } in a local storage object
3) and observe the button if the follow gets rejected
4) If rejected delete the { userId: timeStamp } from the local storage

and the current behaviour is:
1) While unfollowing
2) append the userId to a local storage string

Also we have to make sure that the old data gets migrated to the new object in some way.

**Comment by IvanRF** [comment]
> Also we have to make sure that the old data gets migrated to the new object in some way.

I just saw in the code that you take `userId` as key. Then, you can change the data type associated with each key. Instead of a `String`, use an `Array` like { userId: { followTimeStamp, unfollowed} }. To migrate, if the data read is a String type, then save the new array with `unfollowed = true`.

**Comment by IvanRF** [comment]
Saving the follow actions will also be useful for the "Skip already once unfollowed profiles" setting.

For now, I use 3rd apps to unfollow accounts. So, if you once followed an account with your extension and then unfollowed with something else, next time they want to follow it with your extension you will not have the `unfollowed` data but since it was "once followed" you can ignore it.

**Comment by tlemens** [comment]
Yes. The follow timestamps will also replace the unfollowed data. When we switch to follow timestamps we will just keep the unfollowed data as it is, so this data is not lost and will be used in addition to the timestamps, but does not get updated any more.

Why do you use 3rd apps to unfollow? Do they have any advantages?

**Comment by IvanRF** [comment]
> Why do you use 3rd apps to unfollow? Do they have any advantages?

For now, I use manageflitter.com because I can order the accounts "Not following back" in a chronological order. However, it only allows you to unfollow 100 accounts per day and you have to pay if you want to "Increase your daily unfollow limit to 2,000". That's when I found your extension and by adding this functionality I will not need a 3rd app.

They also have some interesting functions like
- "Inactive": shows accounts who have not tweeted in the last 30 days
- "Fake following": shows fake (spam) accounts that you are following. (they use a Spam Score percentage)
- "Following Ratio": analyzes followers versus follows.

**Comment by benjaminspak** [comment]
Personally I find I'm still getting enough followers if I post often, and follow/unfollow every two days. My supposition is that if a user does not follow you within a couple of days they are not very active, and therefore not worth having because they will not interact with your content.  ¯_(ツ)_/¯

**Comment by tlemens** [comment]
This option is now available. Thank you guys for participating!

**Comment by IvanRF** [comment]
@tlemens thanks for implementing it! 😃
