### ISSUE TITLE
Does not display for Lists members

### ISSUE THREAD

**Issue by ctlong** [tlemens/twitter-mass-follow#2]
I have been unable to access your extension in my lists' members and subscribers pages. It simply will not display itself.

Major props to you on this plugin man! I've been using `Twitter Mass Follow` for several weeks now, and have found it to be far and away my favorite bulk follow/unfollow tool in the chrome app store to date. The styling, showing the count, and having the option to not follow users who have already been followed – just awesome!

This is only significant bug I have come across. Not sure how big of a change this is, and can understand if you don't feel like you want to do anything about it. Please let me know if it won't be fixed and I will downgrade to using `Twitter Follower`, which (shit as it is) can can run on the lists members.

**Comment by tlemens** [comment]
Thank you for the great feedback and the enhancement suggestion.

I think you are right. The extension should work on those pages. It should basically work on every page with user-profiles. Also on the retweets/likes lists.

The code will get more complex though, because the HTML (dom) for a user-profile is different on those pages.

I will start a rewrite - using ES6 - in about 2 weeks and adding new features. I will than dig deeper and consider this feature for the upcoming version.

**Comment by tlemens** [comment]
@ctlong this should work now
